// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYZG9YHPEx7cje3qkhK-z8mlsn37KuLrw',
    appId: '1:755365928017:web:07cec012f5c6defa8cec70',
    messagingSenderId: '755365928017',
    projectId: 'empatia-track',
    authDomain: 'empatia-track.firebaseapp.com',
    storageBucket: 'empatia-track.appspot.com',
    measurementId: 'G-JEF3R7PG9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPiRGGC3Y-XnhF4C7ureJb6JZRvBPEd1E',
    appId: '1:755365928017:android:8f98b60149c062048cec70',
    messagingSenderId: '755365928017',
    projectId: 'empatia-track',
    storageBucket: 'empatia-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGHpjWXtjd2bdPCA8VJ1hnHOoUWsCFtg',
    appId: '1:755365928017:ios:4dc62568cc9b97638cec70',
    messagingSenderId: '755365928017',
    projectId: 'empatia-track',
    storageBucket: 'empatia-track.appspot.com',
    iosBundleId: 'com.jogoempatia.empatiatrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeGHpjWXtjd2bdPCA8VJ1hnHOoUWsCFtg',
    appId: '1:755365928017:ios:4dc62568cc9b97638cec70',
    messagingSenderId: '755365928017',
    projectId: 'empatia-track',
    storageBucket: 'empatia-track.appspot.com',
    iosBundleId: 'com.jogoempatia.empatiatrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYZG9YHPEx7cje3qkhK-z8mlsn37KuLrw',
    appId: '1:755365928017:web:0133129250d1bc2b8cec70',
    messagingSenderId: '755365928017',
    projectId: 'empatia-track',
    authDomain: 'empatia-track.firebaseapp.com',
    storageBucket: 'empatia-track.appspot.com',
    measurementId: 'G-895CKFPS95',
  );

}